### ISSUE TITLE
entropy score "-Infinity" for passwords containing only non ascii characters

### ISSUE THREAD

**Issue by z11labs** [davidstutz/password-score#2]
I'm currently implementing a passwordmeter including your library and I noticed, that the entropy score is `-Infinity` if the password only contains non ascii characters. 

**Reproduction Details:**

- calculate entropy score for a password like `€` or `ä` or `€ä`

**Affected File:**

- password-score.js

**Debug Information:**

- in the function `calculateBruteForceEntropy()` the variable `base` is set to `0`

https://github.com/davidstutz/password-score/blob/4ca38c447f1e57044a0432729f19c23d5eeb80d3/dist/js/password-score.js#L414

- none of the regular expressions matches with the given password and therefore the value `0` is passed to the method `this.lg(x)`

https://github.com/davidstutz/password-score/blob/4ca38c447f1e57044a0432729f19c23d5eeb80d3/dist/js/password-score.js#L432

- `Math.log(0)` returns the value `-Infinity` which then gets returned as the result

https://github.com/davidstutz/password-score/blob/4ca38c447f1e57044a0432729f19c23d5eeb80d3/dist/js/password-score.js#L393

- the value `-Infinity` gets returned as the entropy score

https://github.com/davidstutz/password-score/blob/4ca38c447f1e57044a0432729f19c23d5eeb80d3/dist/js/password-score.js#L435

**Comment by davidstutz** [comment]
Wow, really thorough issue. Thanks for reporting, will look into it.

**Comment by davidstutz** [comment]
I added an additional regular expression to capture every "other" character, i.e. characters not found so far. Also fixed some keyboard issues.
