### ISSUE TITLE
Score -> interpretation

### ISSUE THREAD

**Issue by luckylooke** [davidstutz/password-score#3]
Hi 

I have not found recommended process how to set interpretations of score.. whether score 20 for example is strong enough or not. Can you please provide some hints how to set this? I know that is is up to me, but I dont know how to decide those values... because in my system user attempting wrong password more then 5 times  in a row will get ban for 15min so maybe even score of 20 is enough for such system as it would take years to break such password. 🤷‍♂ 

Thanks for any hints.
Ctibor

**Comment by davidstutz** [comment]
So you can have a look at the default values in https://github.com/davidstutz/bootstrap-strength-meter as guidance. Alternatively, I recommend generating passwords of different strengths, for example using https://passwordsgenerator.net/, and seeing how they are scored. Currently, I tend towards accepting passwords with a score >200 as strong. Then, >100 could be medium. However, these are just rule of thumbs that I use.

In general, even in your case, I would encourage users to have strong passwords. You cannot be sure that an adversary might find a way to avoid your ban in some way or the other. So even with this system of bans, you should plan with an adversary that has full brute-force access to your system.

**Comment by luckylooke** [comment]
ok, thanks for hints 🙂👍
